"""quality module models

Revision ID: ec404ae4b937
Revises: 20260306_0014
Create Date: 2026-03-07 20:26:02.980525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'ec404ae4b937'
down_revision: Union[str, Sequence[str], None] = '20260306_0014'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_plans',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('audit_area', sa.String(length=200), nullable=False),
    sa.Column('planned_date', sa.Date(), nullable=False),
    sa.Column('auditor', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['auditor'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_plans_audit_area'), 'audit_plans', ['audit_area'], unique=False)
    op.create_index(op.f('ix_audit_plans_auditor'), 'audit_plans', ['auditor'], unique=False)
    op.create_index(op.f('ix_audit_plans_created_by'), 'audit_plans', ['created_by'], unique=False)
    op.create_index(op.f('ix_audit_plans_id'), 'audit_plans', ['id'], unique=False)
    op.create_index(op.f('ix_audit_plans_is_deleted'), 'audit_plans', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_audit_plans_planned_date'), 'audit_plans', ['planned_date'], unique=False)
    op.create_index(op.f('ix_audit_plans_status'), 'audit_plans', ['status'], unique=False)
    op.create_index(op.f('ix_audit_plans_updated_by'), 'audit_plans', ['updated_by'], unique=False)
    op.create_table('gauges',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('gauge_code', sa.String(length=80), nullable=False),
    sa.Column('gauge_name', sa.String(length=200), nullable=False),
    sa.Column('last_calibration_date', sa.Date(), nullable=False),
    sa.Column('next_calibration_due', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('Valid', 'Expired', name='gauge_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gauges_created_by'), 'gauges', ['created_by'], unique=False)
    op.create_index(op.f('ix_gauges_gauge_code'), 'gauges', ['gauge_code'], unique=True)
    op.create_index(op.f('ix_gauges_id'), 'gauges', ['id'], unique=False)
    op.create_index(op.f('ix_gauges_is_deleted'), 'gauges', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_gauges_next_calibration_due'), 'gauges', ['next_calibration_due'], unique=False)
    op.create_index(op.f('ix_gauges_status'), 'gauges', ['status'], unique=False)
    op.create_index(op.f('ix_gauges_updated_by'), 'gauges', ['updated_by'], unique=False)
    op.create_table('management_review_meetings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('meeting_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('participants', sa.Text(), nullable=False),
    sa.Column('agenda', sa.Text(), nullable=False),
    sa.Column('minutes', sa.Text(), nullable=True),
    sa.Column('actions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_management_review_meetings_created_by'), 'management_review_meetings', ['created_by'], unique=False)
    op.create_index(op.f('ix_management_review_meetings_id'), 'management_review_meetings', ['id'], unique=False)
    op.create_index(op.f('ix_management_review_meetings_is_deleted'), 'management_review_meetings', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_management_review_meetings_meeting_date'), 'management_review_meetings', ['meeting_date'], unique=False)
    op.create_index(op.f('ix_management_review_meetings_updated_by'), 'management_review_meetings', ['updated_by'], unique=False)
    op.create_table('ncrs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('reference_type', sa.String(length=100), nullable=False),
    sa.Column('reference_id', sa.BigInteger(), nullable=False),
    sa.Column('reported_by', sa.Integer(), nullable=False),
    sa.Column('reported_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('Open', 'Investigating', 'Closed', name='ncr_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reported_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ncrs_created_by'), 'ncrs', ['created_by'], unique=False)
    op.create_index(op.f('ix_ncrs_id'), 'ncrs', ['id'], unique=False)
    op.create_index(op.f('ix_ncrs_is_deleted'), 'ncrs', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_ncrs_reference_id'), 'ncrs', ['reference_id'], unique=False)
    op.create_index(op.f('ix_ncrs_reference_type'), 'ncrs', ['reference_type'], unique=False)
    op.create_index(op.f('ix_ncrs_reported_by'), 'ncrs', ['reported_by'], unique=False)
    op.create_index(op.f('ix_ncrs_status'), 'ncrs', ['status'], unique=False)
    op.create_index(op.f('ix_ncrs_updated_by'), 'ncrs', ['updated_by'], unique=False)
    op.create_table('audit_reports',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('audit_plan_id', sa.BigInteger(), nullable=False),
    sa.Column('findings', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['audit_plan_id'], ['audit_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_reports_audit_plan_id'), 'audit_reports', ['audit_plan_id'], unique=False)
    op.create_index(op.f('ix_audit_reports_created_by'), 'audit_reports', ['created_by'], unique=False)
    op.create_index(op.f('ix_audit_reports_id'), 'audit_reports', ['id'], unique=False)
    op.create_index(op.f('ix_audit_reports_is_deleted'), 'audit_reports', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_audit_reports_status'), 'audit_reports', ['status'], unique=False)
    op.create_index(op.f('ix_audit_reports_updated_by'), 'audit_reports', ['updated_by'], unique=False)
    op.create_table('capas',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ncr_id', sa.BigInteger(), nullable=False),
    sa.Column('action_type', sa.Enum('Corrective', 'Preventive', name='capa_action_type'), nullable=False),
    sa.Column('responsible_person', sa.Integer(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('Open', 'Closed', name='capa_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ncr_id'], ['ncrs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['responsible_person'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_capas_action_type'), 'capas', ['action_type'], unique=False)
    op.create_index(op.f('ix_capas_created_by'), 'capas', ['created_by'], unique=False)
    op.create_index(op.f('ix_capas_id'), 'capas', ['id'], unique=False)
    op.create_index(op.f('ix_capas_is_deleted'), 'capas', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_capas_ncr_id'), 'capas', ['ncr_id'], unique=False)
    op.create_index(op.f('ix_capas_responsible_person'), 'capas', ['responsible_person'], unique=False)
    op.create_index(op.f('ix_capas_status'), 'capas', ['status'], unique=False)
    op.create_index(op.f('ix_capas_updated_by'), 'capas', ['updated_by'], unique=False)
    op.create_table('root_cause_analyses',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ncr_id', sa.BigInteger(), nullable=False),
    sa.Column('method', sa.Enum('5WHY', 'Fishbone', name='root_cause_method'), nullable=False),
    sa.Column('analysis_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ncr_id'], ['ncrs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_root_cause_analyses_created_by'), 'root_cause_analyses', ['created_by'], unique=False)
    op.create_index(op.f('ix_root_cause_analyses_id'), 'root_cause_analyses', ['id'], unique=False)
    op.create_index(op.f('ix_root_cause_analyses_is_deleted'), 'root_cause_analyses', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_root_cause_analyses_method'), 'root_cause_analyses', ['method'], unique=False)
    op.create_index(op.f('ix_root_cause_analyses_ncr_id'), 'root_cause_analyses', ['ncr_id'], unique=False)
    op.create_index(op.f('ix_root_cause_analyses_updated_by'), 'root_cause_analyses', ['updated_by'], unique=False)
    op.create_table('fai_reports',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('production_order_id', sa.BigInteger(), nullable=False),
    sa.Column('drawing_number', sa.String(length=120), nullable=False),
    sa.Column('revision', sa.String(length=50), nullable=False),
    sa.Column('part_number', sa.String(length=120), nullable=False),
    sa.Column('inspected_by', sa.Integer(), nullable=False),
    sa.Column('inspection_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('Pending', 'Approved', 'Rejected', name='fai_report_status'), nullable=False),
    sa.Column('attachment_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['inspected_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['production_order_id'], ['production_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fai_reports_created_by'), 'fai_reports', ['created_by'], unique=False)
    op.create_index(op.f('ix_fai_reports_drawing_number'), 'fai_reports', ['drawing_number'], unique=False)
    op.create_index(op.f('ix_fai_reports_id'), 'fai_reports', ['id'], unique=False)
    op.create_index(op.f('ix_fai_reports_inspected_by'), 'fai_reports', ['inspected_by'], unique=False)
    op.create_index(op.f('ix_fai_reports_is_deleted'), 'fai_reports', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_fai_reports_part_number'), 'fai_reports', ['part_number'], unique=False)
    op.create_index(op.f('ix_fai_reports_production_order_id'), 'fai_reports', ['production_order_id'], unique=False)
    op.create_index(op.f('ix_fai_reports_status'), 'fai_reports', ['status'], unique=False)
    op.create_index(op.f('ix_fai_reports_updated_by'), 'fai_reports', ['updated_by'], unique=False)
    op.create_table('final_inspections',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('production_order_id', sa.BigInteger(), nullable=False),
    sa.Column('inspected_by', sa.Integer(), nullable=False),
    sa.Column('inspection_date', sa.Date(), nullable=False),
    sa.Column('result', sa.Enum('Pass', 'Fail', name='final_inspection_result'), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['inspected_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['production_order_id'], ['production_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_final_inspections_created_by'), 'final_inspections', ['created_by'], unique=False)
    op.create_index(op.f('ix_final_inspections_id'), 'final_inspections', ['id'], unique=False)
    op.create_index(op.f('ix_final_inspections_inspected_by'), 'final_inspections', ['inspected_by'], unique=False)
    op.create_index(op.f('ix_final_inspections_is_deleted'), 'final_inspections', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_final_inspections_production_order_id'), 'final_inspections', ['production_order_id'], unique=False)
    op.create_index(op.f('ix_final_inspections_result'), 'final_inspections', ['result'], unique=False)
    op.create_index(op.f('ix_final_inspections_updated_by'), 'final_inspections', ['updated_by'], unique=False)
    op.create_table('incoming_inspections',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('grn_id', sa.BigInteger(), nullable=False),
    sa.Column('grn_item_id', sa.BigInteger(), nullable=False),
    sa.Column('inspected_by', sa.Integer(), nullable=False),
    sa.Column('inspection_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('Pending', 'Accepted', 'Rejected', name='incoming_inspection_status'), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['grn_id'], ['grns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['grn_item_id'], ['grn_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inspected_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incoming_inspections_created_by'), 'incoming_inspections', ['created_by'], unique=False)
    op.create_index(op.f('ix_incoming_inspections_grn_id'), 'incoming_inspections', ['grn_id'], unique=False)
    op.create_index(op.f('ix_incoming_inspections_grn_item_id'), 'incoming_inspections', ['grn_item_id'], unique=False)
    op.create_index(op.f('ix_incoming_inspections_id'), 'incoming_inspections', ['id'], unique=False)
    op.create_index(op.f('ix_incoming_inspections_inspected_by'), 'incoming_inspections', ['inspected_by'], unique=False)
    op.create_index(op.f('ix_incoming_inspections_is_deleted'), 'incoming_inspections', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_incoming_inspections_status'), 'incoming_inspections', ['status'], unique=False)
    op.create_index(op.f('ix_incoming_inspections_updated_by'), 'incoming_inspections', ['updated_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incoming_inspections_updated_by'), table_name='incoming_inspections')
    op.drop_index(op.f('ix_incoming_inspections_status'), table_name='incoming_inspections')
    op.drop_index(op.f('ix_incoming_inspections_is_deleted'), table_name='incoming_inspections')
    op.drop_index(op.f('ix_incoming_inspections_inspected_by'), table_name='incoming_inspections')
    op.drop_index(op.f('ix_incoming_inspections_id'), table_name='incoming_inspections')
    op.drop_index(op.f('ix_incoming_inspections_grn_item_id'), table_name='incoming_inspections')
    op.drop_index(op.f('ix_incoming_inspections_grn_id'), table_name='incoming_inspections')
    op.drop_index(op.f('ix_incoming_inspections_created_by'), table_name='incoming_inspections')
    op.drop_table('incoming_inspections')
    op.drop_index(op.f('ix_final_inspections_updated_by'), table_name='final_inspections')
    op.drop_index(op.f('ix_final_inspections_result'), table_name='final_inspections')
    op.drop_index(op.f('ix_final_inspections_production_order_id'), table_name='final_inspections')
    op.drop_index(op.f('ix_final_inspections_is_deleted'), table_name='final_inspections')
    op.drop_index(op.f('ix_final_inspections_inspected_by'), table_name='final_inspections')
    op.drop_index(op.f('ix_final_inspections_id'), table_name='final_inspections')
    op.drop_index(op.f('ix_final_inspections_created_by'), table_name='final_inspections')
    op.drop_table('final_inspections')
    op.drop_index(op.f('ix_fai_reports_updated_by'), table_name='fai_reports')
    op.drop_index(op.f('ix_fai_reports_status'), table_name='fai_reports')
    op.drop_index(op.f('ix_fai_reports_production_order_id'), table_name='fai_reports')
    op.drop_index(op.f('ix_fai_reports_part_number'), table_name='fai_reports')
    op.drop_index(op.f('ix_fai_reports_is_deleted'), table_name='fai_reports')
    op.drop_index(op.f('ix_fai_reports_inspected_by'), table_name='fai_reports')
    op.drop_index(op.f('ix_fai_reports_id'), table_name='fai_reports')
    op.drop_index(op.f('ix_fai_reports_drawing_number'), table_name='fai_reports')
    op.drop_index(op.f('ix_fai_reports_created_by'), table_name='fai_reports')
    op.drop_table('fai_reports')
    op.drop_index(op.f('ix_root_cause_analyses_updated_by'), table_name='root_cause_analyses')
    op.drop_index(op.f('ix_root_cause_analyses_ncr_id'), table_name='root_cause_analyses')
    op.drop_index(op.f('ix_root_cause_analyses_method'), table_name='root_cause_analyses')
    op.drop_index(op.f('ix_root_cause_analyses_is_deleted'), table_name='root_cause_analyses')
    op.drop_index(op.f('ix_root_cause_analyses_id'), table_name='root_cause_analyses')
    op.drop_index(op.f('ix_root_cause_analyses_created_by'), table_name='root_cause_analyses')
    op.drop_table('root_cause_analyses')
    op.drop_index(op.f('ix_capas_updated_by'), table_name='capas')
    op.drop_index(op.f('ix_capas_status'), table_name='capas')
    op.drop_index(op.f('ix_capas_responsible_person'), table_name='capas')
    op.drop_index(op.f('ix_capas_ncr_id'), table_name='capas')
    op.drop_index(op.f('ix_capas_is_deleted'), table_name='capas')
    op.drop_index(op.f('ix_capas_id'), table_name='capas')
    op.drop_index(op.f('ix_capas_created_by'), table_name='capas')
    op.drop_index(op.f('ix_capas_action_type'), table_name='capas')
    op.drop_table('capas')
    op.drop_index(op.f('ix_audit_reports_updated_by'), table_name='audit_reports')
    op.drop_index(op.f('ix_audit_reports_status'), table_name='audit_reports')
    op.drop_index(op.f('ix_audit_reports_is_deleted'), table_name='audit_reports')
    op.drop_index(op.f('ix_audit_reports_id'), table_name='audit_reports')
    op.drop_index(op.f('ix_audit_reports_created_by'), table_name='audit_reports')
    op.drop_index(op.f('ix_audit_reports_audit_plan_id'), table_name='audit_reports')
    op.drop_table('audit_reports')
    op.drop_index(op.f('ix_ncrs_updated_by'), table_name='ncrs')
    op.drop_index(op.f('ix_ncrs_status'), table_name='ncrs')
    op.drop_index(op.f('ix_ncrs_reported_by'), table_name='ncrs')
    op.drop_index(op.f('ix_ncrs_reference_type'), table_name='ncrs')
    op.drop_index(op.f('ix_ncrs_reference_id'), table_name='ncrs')
    op.drop_index(op.f('ix_ncrs_is_deleted'), table_name='ncrs')
    op.drop_index(op.f('ix_ncrs_id'), table_name='ncrs')
    op.drop_index(op.f('ix_ncrs_created_by'), table_name='ncrs')
    op.drop_table('ncrs')
    op.drop_index(op.f('ix_management_review_meetings_updated_by'), table_name='management_review_meetings')
    op.drop_index(op.f('ix_management_review_meetings_meeting_date'), table_name='management_review_meetings')
    op.drop_index(op.f('ix_management_review_meetings_is_deleted'), table_name='management_review_meetings')
    op.drop_index(op.f('ix_management_review_meetings_id'), table_name='management_review_meetings')
    op.drop_index(op.f('ix_management_review_meetings_created_by'), table_name='management_review_meetings')
    op.drop_table('management_review_meetings')
    op.drop_index(op.f('ix_gauges_updated_by'), table_name='gauges')
    op.drop_index(op.f('ix_gauges_status'), table_name='gauges')
    op.drop_index(op.f('ix_gauges_next_calibration_due'), table_name='gauges')
    op.drop_index(op.f('ix_gauges_is_deleted'), table_name='gauges')
    op.drop_index(op.f('ix_gauges_id'), table_name='gauges')
    op.drop_index(op.f('ix_gauges_gauge_code'), table_name='gauges')
    op.drop_index(op.f('ix_gauges_created_by'), table_name='gauges')
    op.drop_table('gauges')
    op.drop_index(op.f('ix_audit_plans_updated_by'), table_name='audit_plans')
    op.drop_index(op.f('ix_audit_plans_status'), table_name='audit_plans')
    op.drop_index(op.f('ix_audit_plans_planned_date'), table_name='audit_plans')
    op.drop_index(op.f('ix_audit_plans_is_deleted'), table_name='audit_plans')
    op.drop_index(op.f('ix_audit_plans_id'), table_name='audit_plans')
    op.drop_index(op.f('ix_audit_plans_created_by'), table_name='audit_plans')
    op.drop_index(op.f('ix_audit_plans_auditor'), table_name='audit_plans')
    op.drop_index(op.f('ix_audit_plans_audit_area'), table_name='audit_plans')
    op.drop_table('audit_plans')
    # ### end Alembic commands ###